/*
 * This table stores the permanent identity and administrative state
 * of each bus registered in the Arc Transit fleet.
 *
 * Important design rules:
 * - Arc Transit Version 1 supports buses only.
 * - Newly registered buses begin as INACTIVE.
 * - Unit numbers and plate numbers remain unique even after archival.
 * - Records are archived instead of physically deleted.
 * - Java/JPA manages created_at and updated_at.
 * - JPA optimistic locking uses the version column.
 */

CREATE TABLE arc.fleet_units (

    /*
     * Internal database identifier.
     *
     * PostgreSQL generates this value automatically.
     * This is separate from the human-readable unit_number.
     */
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    /*
     * Internal fleet identifier used by staff.
     *
     * Example:
     * BUS-001
     * BUS-002
     *
     * This value must remain unique across active and archived records.
     */
    unit_number VARCHAR(30) NOT NULL,

    /*
     * Official vehicle registration plate number.
     *
     * This value must remain unique across active and archived records
     * so historical records always refer to one physical bus.
     */
    plate_number VARCHAR(20) NOT NULL,

    /*
     * Vehicle classification.
     *
     * Arc Transit Version 1 supports buses only.
     * The column remains in the schema so additional vehicle types
     * may be introduced later through another Flyway migration.
     */
    vehicle_type VARCHAR(30) NOT NULL DEFAULT 'BUS',

    /*
     * Maximum supported passenger capacity.
     *
     * A bus cannot have a capacity of zero or a negative value.
     */
    capacity SMALLINT NOT NULL,

    /*
     * Current administrative availability of the bus.
     *
     * A newly created bus begins as INACTIVE so registration alone
     * does not automatically make it available for dispatch.
     *
     * Allowed values:
     * - ACTIVE
     * - INACTIVE
     * - UNDER_MAINTENANCE
     * - OUT_OF_SERVICE
     */
    operational_status VARCHAR(30) NOT NULL DEFAULT 'INACTIVE',

    /*
     * Record creation timestamp.
     *
     * Spring Data JPA auditing will assign this value using Java Instant.
     * PostgreSQL stores the value as TIMESTAMPTZ.
     */
    created_at TIMESTAMPTZ NOT NULL,

    /*
     * Most recent record modification timestamp.
     *
     * Spring Data JPA auditing updates this value.
     * No PostgreSQL update trigger is used.
     */
    updated_at TIMESTAMPTZ NOT NULL,

    /*
     * Soft-delete or archival timestamp.
     *
     * NULL:
     * The fleet unit is not archived.
     *
     * Non-NULL:
     * The fleet unit has been archived but remains stored for
     * dispatch, incident, maintenance, and audit history.
     */
    archived_at TIMESTAMPTZ,

    /*
     * JPA optimistic-lock counter.
     *
     * New records begin at version 0.
     * JPA automatically increments this value after successful updates.
     * An update using an outdated version will be rejected.
     */
    version BIGINT NOT NULL DEFAULT 0,

    /*
     * Primary-key constraint.
     */
    CONSTRAINT pk_fleet_units
        PRIMARY KEY (id),

    /*
     * Permanently reserves each unit number.
     *
     * Archived fleet units do not release their unit numbers for reuse.
     */
    CONSTRAINT ux_fleet_unit_number
        UNIQUE (unit_number),

    /*
     * Permanently reserves each plate number.
     *
     * Archived fleet units do not release their plate numbers for reuse.
     */
    CONSTRAINT ux_fleet_plate_number
        UNIQUE (plate_number),

    /*
     * keep as 'BUS' only.
     */
    CONSTRAINT ck_fleet_vehicle_type
        CHECK (vehicle_type = 'BUS'),

    /*
     * Prevents zero or negative passenger capacity.
     */
    CONSTRAINT ck_fleet_capacity_positive
        CHECK (capacity > 0),

    /*
     * Rejects unknown or incorrectly spelled operational states.
     *
     * Full workflow transitions will be controlled by the Java
     * FleetApplicationService. This database constraint only guarantees
     * that stored values belong to the accepted status list.
     */
    CONSTRAINT ck_fleet_operational_status
        CHECK (
            operational_status IN (
                'ACTIVE',
                'INACTIVE',
                'UNDER_MAINTENANCE',
                'OUT_OF_SERVICE'
            )
        )
);