/*
 * Tables:
 * - roles
 * - app_users
 * - user_roles
 *
 * Important rules:
 * - Only SYSTEM_ADMIN and OPERATIONS_STAFF roles exist.
 * - Role definitions are seeded by Flyway.
 * - Staff passwords are stored only as BCrypt hashes.
 * - Drivers are operational records and do not automatically receive accounts.
 * - Java/JPA will manage application timestamps.
 * - User records are archived instead of physically deleted.
 */

CREATE TABLE arc.roles (

    /*
     * Stable code used by Spring Security and authorization checks.
     *
     * Examples:
     * SYSTEM_ADMIN
     * OPERATIONS_STAFF
     */
    role_code VARCHAR(40) NOT NULL,

    /*
     * Human-readable name displayed by the application.
     */
    role_name VARCHAR(80) NOT NULL,

    /*
     * Optional summary explaining the role's responsibility.
     */
    description VARCHAR(255),

    CONSTRAINT pk_roles
        PRIMARY KEY (role_code),

    /*
     * Version 1 accepts only the two documented role definitions.
     * Adding another role later requires a deliberate Flyway migration.
     */
    CONSTRAINT ck_roles_role_code
        CHECK (
            role_code IN (
                'SYSTEM_ADMIN',
                'OPERATIONS_STAFF'
            )
        )
);


CREATE TABLE arc.app_users (

    /*
     * Internal database identity for an authenticated staff account.
     */
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    /*
     * Lowercase login name.
     *
     * Examples:
     * system.admin
     * operations.staff
     */
    username VARCHAR(50) NOT NULL,

    /*
     * BCrypt password hash.
     *
     * A plaintext password must never be stored here.
     */
    password_hash VARCHAR(100) NOT NULL,

    /*
     * Staff name displayed in the application.
     */
    display_name VARCHAR(120) NOT NULL,

    /*
     * Optional contact email.
     *
     * Uniqueness is checked without case sensitivity by an index below.
     */
    email VARCHAR(254),

    /*
     * Current authentication state.
     *
     * ACTIVE:
     * The user may authenticate.
     *
     * DISABLED:
     * Administratively prevented from authenticating.
     *
     * LOCKED:
     * Temporarily or automatically locked.
     */
    account_status VARCHAR(20) NOT NULL,

    /*
     * Most recent successful authentication timestamp.
     *
     * NULL means the user has never successfully logged in.
     */
    last_login_at TIMESTAMPTZ,

    /*
     * Java/JPA-managed creation timestamp.
     */
    created_at TIMESTAMPTZ NOT NULL,

    /*
     * Java/JPA-managed modification timestamp.
     */
    updated_at TIMESTAMPTZ NOT NULL,

    /*
     * Soft-deactivation timestamp.
     *
     * Archived accounts remain stored for authorization
     * and audit-history references.
     */
    archived_at TIMESTAMPTZ,

    /*
     * JPA optimistic-lock version.
     */
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_app_users
        PRIMARY KEY (id),

    /*
     * Usernames remain permanently reserved, including after archival.
     */
    CONSTRAINT ux_app_users_username
        UNIQUE (username),

    /*
     * Prevents mixed-case login names.
     *
     * Example accepted:
     * operations.staff
     *
     * Example rejected:
     * Operations.Staff
     */
    CONSTRAINT ck_app_users_username_lowercase
        CHECK (username = LOWER(username)),

    /*
     * Prevents blank usernames.
     */
    CONSTRAINT ck_app_users_username_not_blank
        CHECK (BTRIM(username) <> ''),

    /*
     * Prevents blank display names.
     */
    CONSTRAINT ck_app_users_display_name_not_blank
        CHECK (BTRIM(display_name) <> ''),

    /*
     * Prevents an empty password-hash value.
     *
     * Actual BCrypt validation remains the responsibility
     * of the Java authentication setup.
     */
    CONSTRAINT ck_app_users_password_hash_not_blank
        CHECK (BTRIM(password_hash) <> ''),

    /*
     * Rejects unknown account states.
     */
    CONSTRAINT ck_app_users_account_status
        CHECK (
            account_status IN (
                'ACTIVE',
                'DISABLED',
                'LOCKED'
            )
        )
);


/*
 * Enforces case-insensitive email uniqueness when an email exists.
 *
 * Example:
 * staff@arctransit.local
 * STAFF@ARCTRANSIT.LOCAL
 *
 * PostgreSQL treats these as the same email for uniqueness purposes.
 * Multiple NULL values remain allowed because email is optional.
 */
CREATE UNIQUE INDEX ux_app_users_email_ci
    ON arc.app_users (LOWER(email))
    WHERE email IS NOT NULL;


CREATE TABLE arc.user_roles (

    /*
     * Staff account receiving the role.
     */
    user_id BIGINT NOT NULL,

    /*
     * Seeded role assigned to the account.
     */
    role_code VARCHAR(40) NOT NULL,

    /*
     * Administrator who granted the role.
     *
     * NULL is permitted for controlled system setup,
     * including the first development administrator.
     */
    assigned_by_user_id BIGINT,

    /*
     * Java/JPA-managed role-assignment timestamp.
     */
    assigned_at TIMESTAMPTZ NOT NULL,

    /*
     * Prevents the same role from being assigned
     * to the same account more than once.
     */
    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role_code),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES arc.app_users (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_code)
        REFERENCES arc.roles (role_code)
        ON DELETE RESTRICT,

    /*
     * SET NULL preserves the assignment record if its optional
     * administrator reference is ever removed during controlled cleanup.
     *
     * Normal application behavior still archives users instead of
     * physically deleting them.
     */
    CONSTRAINT fk_user_roles_assigned_by
        FOREIGN KEY (assigned_by_user_id)
        REFERENCES arc.app_users (id)
        ON DELETE SET NULL
);


/*
 * Seed the fixed Version 1 role definitions.
 *
 * Administrators assign these roles to accounts but do not
 * create new role definitions through the user interface.
 */
INSERT INTO arc.roles (
    role_code,
    role_name,
    description
)
VALUES
    (
        'SYSTEM_ADMIN',
        'System Administrator',
        'Manages staff accounts, role assignments, configuration, audit records, and all operational modules.'
    ),
    (
        'OPERATIONS_STAFF',
        'Operations Staff',
        'Handles daily fleet, route, dispatch, incident, maintenance, status, and dashboard operations.'
    );